### PR TITLE
Modern MessageBox and KeyboardInput

### LINKED ISSUE #3313: Guide doesn't work on WP8.1
Because BeginInvoke is not supported.

### PR DESCRIPTION
**Pull request by Nezz**
Uses async/await
Implemented for Android, iOS, Windows Phone 8, Windows 8 and Windows Phone 8.1
Added cancellation support (works everywhere except on WP8 where we can make it work if we use our custom XAML implementation instead of the XNA one)
Fixes #3313

### CODE REVIEW

**Comment by Nezz** [comment]
@tomspilman Does this look good to you?

**Comment by Nezz** [comment]
This needs to be updated to work with the new Xamarin Unified API.

**Comment by Nezz** [comment]
Done.

**Comment by Nezz** [comment]
The build has failed because it didn't contain the other parts for the unified api. Looks like i'll have to rebase it.
```error CS0246: The type or namespace name `NSNotification' could not be found. Are you missing `MonoTouch.Foundation' using directive?```
