### ISSUE TITLE
PixelShader Custom Structure is not working.

### ISSUE THREAD

**Issue by Praptobala** [mono/MonoGame#4760]
```
struct PixelShaderOutput
{
	float4 color : COLOR0;
	float depth : DEPTH0;
};

PixelShaderOutput PixelShaderFunction(VertexShaderOutput input)
{
	PixelShaderOutput pixOut;

	pixOut.depth = //Assign Depth value
	pixOut.color = //Assign Color value

	return pixOut;
}

```
I need depth data per pixel for depth Rendering , currently I am porting my XNA project to Monogame.
Everything was working fine with XNA4.0.

But Monogame gives compilation error for the above Pixel Shader function, but the same function working fine if I return only 'float4' from it. Please help in this regard.

**Comment by tomspilman** [comment]
> But Monogame gives compilation error for the above Pixel Shader function

What is the error message?

**Comment by Praptobala** [comment]
Hi Tom, Thanks for your swift reply!

The error has gone now.. I think earlier I was having COLOR0 at the end of the function, that was causing the issue I guess, 

PixelShaderOutput PixelShaderFunction(VertexShaderOutput input) : COLOR0
{
}

Now I removed it and its compiling fine. Thanks :)

**Comment by tomspilman** [comment]
> I think earlier I was having COLOR0 at the end of the function

Yeah... that could do it.  Thanks for letting us know it was solved.

**Comment by Praptobala** [comment]
But now its running but gives me black screen.. Can you tell me why?

**Comment by tomspilman** [comment]
Could be lots of different things...  usually it takes some trial and error to work it out.

 - Is your render state wrong... depth clipping enabled, blending?
 - Does your geometry vertex format match the expected inputs to the vertex shader?
 - Is the triangle winding order backwards and the geometry getting culled?
 - Are you forgetting to set any uniforms from your code?
 - Does your vertex shader outputs exactly match your pixel shader inputs.
 - Are you not setting the textures correctly causing it to read a black/null texture?
 - Are you drawing over the results with another shader? 

Usually running with the DirectX graphics debugger built into newer releases of Visual Studio lets you capture a frame of your running game and examine it in detail.  That is usually what I do when I can't figure out why something isn't rendering.
